name: Cargo Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Cargo Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal --target wasm32-wasip2

      - name: Build
        run: cargo build --locked --target wasm32-wasip2
